// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using tracking_code_api;

#nullable disable

namespace tracking_code_api.Migrations
{
    [DbContext(typeof(MotosDbContext))]
    [Migration("20250924215304_TornarTagOpcional")]
    partial class TornarTagOpcional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tracking_code_api.Entities.AuditoriaMovimentacao", b =>
                {
                    b.Property<int>("IdAudit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_audit");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAudit"));

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_operacao");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_funcionario");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("tipo_operacao");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("valores_anteriores");

                    b.Property<string>("ValoresNovos")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("valores_novos");

                    b.HasKey("IdAudit");

                    b.HasIndex("IdFuncionario");

                    b.ToTable("AUDITORIA_MOVIMENTACAO", (string)null);
                });

            modelBuilder.Entity("tracking_code_api.Entities.Localizacao", b =>
                {
                    b.Property<int>("IdLocalizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_localizacao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalizacao"));

                    b.Property<string>("CodigoTag")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("codigo_tag");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_registro");

                    b.Property<int>("IdSetor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_setor");

                    b.Property<decimal>("X")
                        .HasPrecision(12, 8)
                        .HasColumnType("DECIMAL(12,8)")
                        .HasColumnName("x");

                    b.Property<decimal>("Y")
                        .HasPrecision(12, 8)
                        .HasColumnType("DECIMAL(12,8)")
                        .HasColumnName("y");

                    b.HasKey("IdLocalizacao");

                    b.HasIndex("CodigoTag");

                    b.HasIndex("IdSetor");

                    b.ToTable("LOCALIZACAO", (string)null);
                });

            modelBuilder.Entity("tracking_code_api.Entities.Moto", b =>
                {
                    b.Property<string>("Chassi")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("chassi");

                    b.Property<string>("CodigoTag")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("codigo_tag");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_cadastro");

                    b.Property<int?>("IdAudit")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_audit");

                    b.Property<int>("IdSetor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_setor");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("placa");

                    b.HasKey("Chassi");

                    b.HasIndex("CodigoTag")
                        .IsUnique()
                        .HasFilter("\"codigo_tag\" IS NOT NULL");

                    b.HasIndex("IdAudit");

                    b.HasIndex("IdSetor");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasFilter("\"placa\" IS NOT NULL");

                    b.ToTable("MOTO", (string)null);
                });

            modelBuilder.Entity("tracking_code_api.Entities.Setor", b =>
                {
                    b.Property<int>("IdSetor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_setor");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSetor"));

                    b.Property<double?>("CoordenadasLimite")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("coordenadas_limite");

                    b.Property<string>("Descricao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("nome");

                    b.HasKey("IdSetor");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("SETOR", (string)null);
                });

            modelBuilder.Entity("tracking_code_api.Entities.Tag", b =>
                {
                    b.Property<string>("CodigoTag")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("codigo_tag");

                    b.Property<string>("Chassi")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("chassi");

                    b.Property<DateTime>("DataVinculo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_vinculo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status");

                    b.HasKey("CodigoTag");

                    b.ToTable("TAG", (string)null);
                });

            modelBuilder.Entity("tracking_code_api.Entities.Usuario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_funcionario");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuncionario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("email");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("funcao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("senha");

                    b.HasKey("IdFuncionario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("tracking_code_api.Entities.AuditoriaMovimentacao", b =>
                {
                    b.HasOne("tracking_code_api.Entities.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("tracking_code_api.Entities.Localizacao", b =>
                {
                    b.HasOne("tracking_code_api.Entities.Tag", "Tag")
                        .WithMany("Localizacoes")
                        .HasForeignKey("CodigoTag")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tracking_code_api.Entities.Setor", "Setor")
                        .WithMany("Localizacoes")
                        .HasForeignKey("IdSetor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("tracking_code_api.Entities.Moto", b =>
                {
                    b.HasOne("tracking_code_api.Entities.Tag", "Tag")
                        .WithOne("Moto")
                        .HasForeignKey("tracking_code_api.Entities.Moto", "CodigoTag");

                    b.HasOne("tracking_code_api.Entities.AuditoriaMovimentacao", "Auditoria")
                        .WithMany()
                        .HasForeignKey("IdAudit");

                    b.HasOne("tracking_code_api.Entities.Setor", "Setor")
                        .WithMany("Motos")
                        .HasForeignKey("IdSetor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auditoria");

                    b.Navigation("Setor");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("tracking_code_api.Entities.Setor", b =>
                {
                    b.Navigation("Localizacoes");

                    b.Navigation("Motos");
                });

            modelBuilder.Entity("tracking_code_api.Entities.Tag", b =>
                {
                    b.Navigation("Localizacoes");

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("tracking_code_api.Entities.Usuario", b =>
                {
                    b.Navigation("Auditorias");
                });
#pragma warning restore 612, 618
        }
    }
}
